### ISSUE TITLE
Attemptid not retrieved in regular expression

### ISSUE THREAD

**Issue by plindgreen** [YU-MITC/jmeter-quiz-testplan#1]
Step 101 under Start Quiz , mod/quiz/startattempt.php , regular expression to extract 'attemptid' did not work, attempt=(\d*). Tried extracting from 'main sample only' and 'main sample and Sub samples'

startattempt.php normally redirects to a couple pages, ending up at attempt.php when I manually do a quiz, with the attempt id in the url of atempt.php. Listener View Results Tree does not indicate any content with the attemptid to extract?

im using moodle 3.5 and jmeter 5.

**Comment by YU-MITC** [comment]
Hello @plindgreen,
Thank you for your report.

We can start the quiz normally under the JMeter 5.2 and the Moodle 3.5-3.9.

Before the beginning of the quiz, the web browser cannot find the attempt ID in content of "mod/quiz/view.php".
Then, the JMeter execute the step 101.
After some redirections, "/mod/quiz/startattempt.php" prints question(s).
Response content of the "startattempt.php" includes some URLs about the quiz.
These URLs include the attempt ID (ex. attempt=12345).
In the Moodle 3.1 and later versions, the response content includes "quibaid".
So that, we extracts the "attempt" and the "qubaid" from response content of step 101.

Regards,

**Comment by plindgreen** [comment]
Hi, 

Ive included the Response Body screenshots for step 101, did not find any reference to 'attempt' in all three pages, do you see the same as in the screenshots below? When I manually take the exam questions appear on attempt.php, not startattempt.php (see last screenshot), attempt.php does have many references to the attempt number, but it requires attempt id to get there.

Thanks

![Git101](https://user-images.githubusercontent.com/26714950/99705307-eebc8200-2a6f-11eb-8e68-7aba6b570dfb.GIF)
![Git101b](https://user-images.githubusercontent.com/26714950/99705309-ef551880-2a6f-11eb-8393-fdbbb46bf82b.GIF)
![Git101c](https://user-images.githubusercontent.com/26714950/99705298-ecf2be80-2a6f-11eb-9f72-b9e8d19c795a.GIF)

![Git116](https://user-images.githubusercontent.com/26714950/99705302-ed8b5500-2a6f-11eb-8153-626364ab7e37.GIF)
![GitAttemptID](https://user-images.githubusercontent.com/26714950/99705303-ee23eb80-2a6f-11eb-9ed0-98fdfbda4454.GIF)
![GitAttemptPhp](https://user-images.githubusercontent.com/26714950/99705306-ee23eb80-2a6f-11eb-8f3c-5a075451e16e.GIF)

**Comment by YU-MITC** [comment]
Hello @plindgreen,

Redirection from "startattempt.php" to "attempt.php" does not affect result of load test.
Because, response content of "attempt.php" is transmitted as response of step 101, even if the redirections occur.

Do you execute your load tests on GUI mode?
After setting of "User Defined Variables" (site URL, courseid, cmid, etc.), you should execute your load tests using command line (please see sections 4-6 of installation manual).

The load tests using the GUI rewrite our test plan file.
In the GUI mode, URL and parameters of each step are modified after execution of the step.
Many parameters (ex. user ID, session ID, attempt ID, etc.) must be set as variables.
But, execution of each step changes the variables to certain values according to response.
And, after the parameter values are changed to certain values for a user, those values are used in another user's step.
Such a rewrite mechanism is not suitable for repeated tests or multi-user environments.
So that, response content viewed in the GUI mode is not appropriate as a basis for determining defects.

So, you should execute your load tests on command line mode.

Regards,

**Comment by plindgreen** [comment]
you are correct, ran the script in command line and everything looks great !

thank you for producing this amazing script and responding to my gui/cmd mistake. Im sure others will start using this script once word gets out..Im going to promote it in the moodle community

**Comment by YU-MITC** [comment]
Hello @plindgreen,

We are happy that your load test worked fine.
In order to adjust the load on the server, it is recommended to change the "post_var" (range of time to send the answer, defined in test plan file) or "client" (the number of users, defined in command line parameter).

Regards,
