### ISSUE TITLE
Help required to replicate

### ISSUE THREAD

**Issue by arbitrarymahi** [YU-MITC/jmeter-quiz-testplan#2]
Hello @YU-MITC ,

I have followed the test plan you provided and successfully tested our institute moodle. Now we want to test the moodle for multiple pages quiz as well. Can you please help in creating the JMX script and how to do that for multiple users. Any tutorial or resources and tools that you used will be very helpful. 

Thanks,

**Comment by YU-MITC** [comment]
We're sorry for late response.
We only use the JMeter in order to create our test plan.
JMeter proxy (a component of JMeter) can record HTTP queries.
At first, we went to our test Moodle site via the JMeter proxy, and did a series of operations.
The JMeter proxy created a JMX file includes HTTP queries and responses.
Then, we modified the JMX file manually.
The modification process is very long and complicated.
It is difficult for us to explain these details.
